#!/usr/bin/python3

import sys
from src.DockerWrapper import DockerWrapper
        
def main(argv):
    '''
        Docker-helper
        attach     attach to a container running
        delete     container/image delete container according to the number you specified
        delete-all container/image delete all container running or exited
    '''
    dockerwrapper = DockerWrapper()
    if len(argv) is 0:
        print(main.__doc__)

    elif argv[0] == "delete":
        '''
            delete     delete container according to the number you specified
        '''
        if argv[1] == "container":
            containers = dockerwrapper.list_containers()
            num = len(containers)
            dockerwrapper.print_containers(containers)
            # if containers num is zero means no container could be deleted
            if num is 0:
                print("No Container could be removed")
                return

            str = input("Container number you want to delete: ");
            if not str:
                return
            if int(str) > num - 1:
                print("wrong container number {0}".format(str))
                return
            container_number = dockerwrapper.get_container_id(containers[int(str)])
            dockerwrapper.delete_container(container_number)

        elif argv[1] == "image":
            images = dockerwrapper.list_images()
            num = len(images)
            dockerwrapper.print_images(images)
            if num is 0:
                print("No Image could be removed")
                return

            str = input("Image number you want to delete: ");
            if not str:
                return
            if int(str) > num - 1:
                print("wrong Image number {0}".format(str))
                return
            image_id = dockerwrapper.get_image_id(images[int(str)])
            dockerwrapper.delete_image(image_id)
            return

    elif argv[0] == "deleteall":
        '''
            delete-all delete all container running or exited
        '''
        if argv[1] == "container":
            containers = dockerwrapper.list_containers()
            dockerwrapper.print_containers(containers)
            # if containers num is zero means no container could be deleted
            if len(containers) is 0:
                print("No containers will be deleted\n\n")
                return
            print("these containers will be deleted\n")

            #chose delete or not , this is last chance to regret :)
            str = input("Delete all these containers?Y/N: ")
            if str is "Y" or str is "y":
                for container in containers:
                    number = dockerwrapper.get_container_id(container)
                    dockerwrapper.delete_container(number)
            else:
                return

        elif argv[1] == "image":
            return


    elif argv[0] == "attach":
        containers = dockerwrapper.list_up_containers()
        num = len(containers)
        dockerwrapper.print_containers(containers)

        #if containers num is zero means no container could be attached
        if num is 0:
            print("No Container could be attached")
            return

        # choose container number to attach
        str = input("Container number you want to attach: ");
        if not str:
            return
        if int(str) > num - 1:
            print("wrong container number {0}".format(str))
            return
        container_number = dockerwrapper.get_container_id(containers[int(str)])
        print(container_number)
        dockerwrapper.attach_container(container_number)


    else:
        print("\n[error] : command {0} isn't supported".format(argv[0]))
        print(main.__doc__)


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
