#!/usr/bin/python3

import sys
import subprocess
import re

class DockerWrapper:
    board = "Num\t CONTAINER ID        IMAGE                                                 " \
            "COMMAND             CREATED             STATUS                       PORTS               NAMES"

    def list_images(self):
        output = subprocess.check_output(["docker", "images"]).decode("utf-8")
        return output.split("\n")

    def list_containers(self):
        output = subprocess.check_output(["docker", "ps", "-a"]).decode("utf-8")
        return output.split("\n")[1:-1]

    def list_up_containers(self):
        containers = self.list_containers()
        rcontainers = []
        for container in containers:
            if re.search("Up",container) is not None:
                rcontainers.append(container)
        return rcontainers

    def list_containers_number(self):
        output = subprocess.check_output(["docker", "ps", "-aq"]).decode("utf-8")
        return output.split("\n")[:-1]

    def delete_container(self, container):
        output = subprocess.check_output(["docker", "rm", "-f", container]).decode("utf-8")

    def get_container_id(self, container_str):
        return container_str.split()[0];

    def print_containers(self, containers):
        num = 0
        print(self.board)
        for container in containers:
            print("{0}\t {1}".format(num,container))
            num += 1

    def attach_container(self, container):
        subprocess.call(["docker", "attach", container])
        
def main(argv):
    '''
        Docker-helper
        attach     attach to a container running
        delete     delete container according to the number you specified
        delete-all delete all container running or exited
    '''
    dockerwrapper = DockerWrapper()
    if len(argv) is 0:
        print(main.__doc__)

    elif argv[0] == "delete":
        '''
            delete     delete container according to the number you specified
        '''
        containers = dockerwrapper.list_containers()
        num = len(containers)
        dockerwrapper.print_containers(containers)
        # if containers num is zero means no container could be deleted
        if num is 0:
            print("No Container could be removed")
            return

        str = input("Container number you want to delete: ");
        print(str)
        if not str:
            return
        if int(str) > num - 1:
            print("wrong container number {0}".format(str))
            return
        container_number = dockerwrapper.get_container_id(containers[int(str)])
        dockerwrapper.delete_container(container_number)

    elif argv[0] == "deleteall":
        '''
            delete-all delete all container running or exited
        '''
        containers = dockerwrapper.list_containers()
        dockerwrapper.print_containers(containers)
        # if containers num is zero means no container could be deleted
        if len(containers) is 0:
            print("No containers will be deleted\n\n")
            return
        print("these containers will be deleted\n")

        #chose delete or not , this is last chance to regret :)
        str = input("Delete all these containers?Y/N: ")
        if str is "Y" or str is "y":
            for container in containers:
                number = dockerwrapper.get_container_id(container)
                dockerwrapper.delete_container(number)
        else:
            return


    elif argv[0] == "attach":
        containers = dockerwrapper.list_up_containers()
        num = len(containers)
        dockerwrapper.print_containers(containers)

        #if containers num is zero means no container could be attached
        if num is 0:
            print("No Container could be attached")
            return

        # choose container number to attach
        str = input("Container number you want to attach: ");
        if not str:
            return
        if int(str) > num - 1:
            print("wrong container number {0}".format(str))
            return
        container_number = dockerwrapper.get_container_id(containers[int(str)])
        print(container_number)
        dockerwrapper.attach_container(container_number)


    else:
        print("\n[error] : command {0} isn't supported".format(argv[0]))
        print(main.__doc__)


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
